# Generated by Django 4.1.3 on 2023-06-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item_secription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_secription',
            new_name='menu_item_decription',
        ),
    ]
