# Generated by Django 4.1.3 on 2023-06-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_menu_item_secription_menu_menu_item_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_decription',
            new_name='menu_item_description',
        ),
    ]
